[features]
seeds = false
[programs.localnet]
ido = "AUuf3MCis1CgAsFXHgson2r3g4VjqUdD7r3CUc8mEKj3"
[programs.devnet]
ido = "AUuf3MCis1CgAsFXHgson2r3g4VjqUdD7r3CUc8mEKj3"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
