[features]
seeds = false
[programs.localnet]
ido = "Hxcws9iykaMYStaLJhHiz3RtxqrpgfjMxaarRoGVan5q"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/anon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
